"use strict"

/* 
	This file is part of TAPIS. TAPIS is a web page and a Javascript code 
	that builds queries and explore the STAplus content, saves it as CSV or 
	GeoJSON and connects with the MiraMon Map Browser. While the project is 
	completely independent from the Orange data mining software, it has been 
	inspired by its GUI. The general idea of the application is to be able 
	to work with STA data as tables.
  
	The TAPIS client is free software under the terms of the MIT License

	Copyright (c) 2023-2026 Joan Masó

	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:

	The above copyright notice and this permission notice shall be included in all
	copies or substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
	SOFTWARE.
	
	The TAPIS can be updated from https://github.com/grumets/tapis.

	Aquest codi JavaScript ha estat idea de Joan Masó Pau (joan maso at uab cat) 
	dins del grup del MiraMon. MiraMon és un projecte del 
	CREAF que elabora programari de Sistema d'Informació Geogràfica 
	i de Teledetecció per a la visualització, consulta, edició i anàlisi 
	de mapes ràsters i vectorials. Aquest progamari programari inclou
	aplicacions d'escriptori i també servidors i clients per Internet.
	No tots aquests productes són gratuïts o de codi obert. 
	
	En particular, el TAPIS es distribueix sota els termes de la llicència MIT.
	
	El TAPIS es pot actualitzar des de https://github.com/grumets/tapis.
*/


const ServicesAndAPIs = {
	sta: { name: "STA plus", description: "STA service", startNode: true, help: "Connects to a SensorThings API or a STAplus instance and returns a table with the list of entities suported by the API." },
	ogcAPICols: { name: "OGC API collections", description: "OAPI Collections", startNode: true, help: "Connects to the collections page of a OGC Web API instance and returns a table with the list collections available." },
	ogcAPIItems: { name: "OGC API items", description: "OAPI items", help: "Connects to a collection page on an OGC Web API Features or derivatives and returns a table with the items available. One of the columns contains the geometry JSON object." },
	csw: { name: "Catalogue", description: "OGC CSW", startNode: true, help: "Connects to a OGC CSW cataloge service. The result is a table with a list of records in the catalogue that have data associated with them." },
	s3Service: { name: "S3 Service", description: "S3 Service", startNode: true, help: "Connects to a Amazon S3 compatible service (e.g. MinIO) and return the list of buckets available as a table." },
	s3Bucket: { name: "S3 Bucket", description: "S3 Bucket", help: "Connects to a Amazon S3 backet (e.g. MinIO) and return the list of files available (in the root folder and all subfolders as a table." },
	edc: { name: "DataSpace cat.", description: "DataSpace cat.", startNode: true, help: "Connects to an Eclipse Data Connector (EDC) Catalogue and returns the list of assets available as a table." },
	edcAsset: { name: "DataSpace asset", description: "DataSpace asset", help: "Prepares an Eclipse Data Connector (EDC) Asset." },
	ImportCSV: { name: "CSV", description: "CSV", startNode: true, help: "Imports data from a CSV file and returns a table." },
	ImportDBF: { name: "DBF", description: "DBF", startNode: true, help: "Imports data from a DBASE III+, IV or a extended DBF file and returns a table." },
	ImportGPKG: { name: "GeoPackage", description: "GeoPackage", startNode: true, help: "Imports a GeoPackage Database into a list of of tables." },
	ImportGPKGTable: { name: "GeoPackageTable", description: "GeoPack Table", help: "Imports a table in a GeoPackage database." },
	ImportJSONLD: { name: "JSON-LD", description: "JSON-LD", startNode: true, help: "Imports data from a JSON-LD file and returns a table." },
	ImportJSON: { name: "JSON", description: "JSON", startNode: true, help: "Imports data from a JSON file and returns a table." },
	ImportGeoJSON: { name: "GeoJSON", description: "GeoJSON", startNode: true, help: "Imports the features of a GeoJSON and returns a table where each feature is a record. One of the columns contains the geometry JSON object." },
	CreateDGGS: { name: "Extent", description: "DGGS extent", startNode: true, help: "Create a table of all DGGS codes that are inside a geospatial extent. It can also add the position or the center of the cell." },
	CreateNewTable: { name: "New table", description: "New table", startNode: true, help: "Create a new table from scratch." },
	staRoot: { name: "STA root", description: "STA root", help: "Returns to the root of the SensorThings API or STSTAplus service in use. In other words, removes the path and query parameters of the previous node." }
};
const ServicesAndAPIsArray = Object.keys(ServicesAndAPIs);
const ServicesAndAPIsType = { singular: "Data input tool", plural: "Data input tools" };

const STAEntities = {
	Campaigns: { singular: "Campaign", entities: [{ name: "Datastreams", required: false }, { name: "MultiDatastreams", required: false }, { name: "Party", required: true }, { name: "License", required: false }, { name: "ObservationGroups", required: "false" }], properties: [{ name: "name", dataType: "string", required: true }, { name: "description", dataType: "string", required: true }, { name: "classification", dataType: "string", required: false }, { name: "termsOfUse", dataType: "string", required: true }, { name: "privacyPolicy", dataType: "string", required: false }, { name: "creationTime", dataType: "isodatetime", required: true }, { name: "url", dataType: "URI", required: false }, { name: "startTime", dataType: "isodatetime", required: false }, { name: "endTime", dataType: "isodatetime", required: false }, { name: "properties", dataType: "JSON", required: false }], help: "Visualize through a table the Campaigns of this STAPlus service.", helpEdit: "Create, edit or delete an Campaign in a STAPlus service." },
	Cells: { singular: "Cell", entities: [{ name: "Datastreams", required: false }, { name: "MultiDatastreams", required: false }, { name: "Observations", required: false }], properties: [{ name: "system", dataType: "string", required: true }, { name: "resolution", dataType: "string", required: false }, { name: "properties", dataType: "JSON", required: false }], help: "Visualize through a table the Cells of this STAPlus service.", helpEdit: "Create, edit or delete a Cell in a STAPlus service." },
	Datastreams: { singular: "Datastream", entities: [{ name: "Party", required: true }, { name: "Sensor", required: true }, { name: "ObservedProperty", required: true }, { name: "Campaigns", required: false }, { name: "License", required: false }, { name: "Observations", required: false }, { name: "Thing", required: true }, { name: "Cells", required: false }], properties: [{ name: "name", dataType: "string", required: true }, { name: "description", dataType: "string", required: true }, { name: "observationType", dataType: "string", required: true }, { name: "unitOfMeasurement", dataType: "JSON", required: true }, { name: "observedArea", dataType: "object", required: false }, { name: "phenomenonTime", dataType: "data_isoperiod", required: false }, { name: "resultTime", dataType: "data_isoperiod", required: false }, { name: "properties", dataType: "JSON", required: false }], help: "Visualize through a table the Datastreams of this STAPlus service.", helpEdit: "Create, edit or delete a Datastream in a STAPlus service." },
	FeaturesOfInterest: { singular: "FeatureOfInterest", entities: [{ name: "Observations", required: false }], properties: [{ name: "name", dataType: "string", required: true }, { name: "description", dataType: "string", required: true }, { name: "encodingType", dataType: "string", required: true }, { name: "feature", dataType: "", required: true }, { name: "properties", dataType: "JSON", required: false }], help: "Visualize through a table the FeaturesOfInterest of this STAPlus service.", helpEdit: "Create, edit or delete a FeatureOFInterest in a STAPlus service." },
	HistoricalLocations: { singular: "HistoricalLocation", entities: [{ name: "Thing", required: true }, { name: "Locations", required: true }], properties: [{ name: "time", dataType: "isodatetime", required: true }], help: "Visualize through a table the HistoricalLocations of this STAPlus service" },
	Licenses: { singular: "License", entities: [{ name: "Datastreams", required: false }, { name: "MultiDatastreams", required: false }, { name: "Campaigns", required: false }, { name: "ObservationGroups", required: false }], properties: [{ name: "name", dataType: "string", required: true }, { name: "definition", dataType: "URI", required: true }, { name: "description", dataType: "string", required: true }, { name: "logo", dataType: "string", required: false }, { name: "attributionText", dataType: "JSON", required: false }], help: "Visualize through a table the Licenses of this STAPlus service.", helpEdit: "Create, edit or delete a License in a STAPlus service." },
	Locations: { singular: "Location", entities: [{ name: "Things", required: false }, { name: "HistoricalLocations", required: false }], properties: [{ name: "name", dataType: "string", required: true }, { name: "description", dataType: "string", required: true }, { name: "encodingType", dataType: "string", required: true }, { name: "location", dataType: "", required: true }, { name: "properties", dataType: "JSON", required: false }], help: "Visualize through a table the Locations of this STAPlus service.", helpEdit: "Create, edit or delete a Location in a STAPlus service." },
	MultiDatastreams: { singular: "MultiDatastream", entities: [{ name: "Party", required: true }, { name: "Sensor", required: true }, { name: "ObservedProperties", required: true }, { name: "Campaigns", required: false }, { name: "License", required: false }, { name: "Observations", required: false }, { name: "Thing", required: true }, { name: "Cells", required: false }], properties: [{ name: "name", dataType: "string", required: true }, { name: "description", dataType: "string", required: true }, { name: "observationType", dataType: "string", required: true }, { name: "unitOfMeasurements", dataType: "JSON", required: true }, { name: " observedArea", dataType: "object", required: false }, { name: "phenomenonTime", dataType: "data_isoperiod", required: false }, { name: "resultTime", dataType: "data_isoperiod", required: false }, { name: "multiObservationDataType", dataType: "JSON", required: true }, { name: "properties", dataType: "JSON", required: false }], help: "Visualize through a table the MultiDatastreams of this STAPlus service.", helpEdit: "Create, edit or delete a MultiDatastream in a STAPlus service." },
	ObservationGroups: { singular: "ObservationGroup", entities: [{ name: "Party", required: true }, { name: "Campaigns", required: false }, { name: "License", required: false }, { name: "Observations", required: false }, { name: "Relations", required: false }], properties: [{ name: "name", dataType: "string", required: true }, { name: "description", dataType: "string", required: true }, { name: "purpose", dataType: "string", required: false }, { name: "creationTime", dataType: "isodatetime", required: false }, { name: "endTime", dataType: "isodatetime", required: false }, { name: "termsOfUsed", dataType: "string", required: false }, { name: "privacyPolicy", dataType: "string", required: false }, { name: "dataQuality", dataType: "JSON", required: false }, { name: "properties", dataType: "JSON", required: false }], help: "Visualize through a table the ObservationGroups of this STAPlus service.", helpEdit: "Create, edit or delete an ObservationGroup in a STAPlus service." },
	Observations: { singular: "Observation", entities: [{ name: "Datastream", required: true }, { name: "MultiDatastream", required: true }, { name: "FeatureOfInterest", required: false }, { name: "ObservationGroups", required: false }, { name: "Cells", required: false }, { name: "Subjects", required: false }, { name: "Objects", required: false }], properties: [{ name: "phenomenonTime", dataType: "object", required: true }, { name: "resultTime", dataType: "isodatetime", required: true }, { name: "result", dataType: "", required: true }, { name: "resultQuality", dataType: "object", required: false }, { name: "validTime", dataType: "data_isoperiod", required: false }, { name: "parameters", dataType: "JSON", required: false }], entityRelations: ["Object", "Subject"], help: "Visualize through a table the Observations of this STAPlus service.", helpEdit: "Create, edit or delete an Observation in a STAPlus service." },
	ObservedProperties: { singular: "ObservedProperty", entities: [{ name: "Datastreams", required: false }, { name: "MultiDatastreams", required: false }], properties: [{ name: "name", dataType: "string", required: true }, { name: "definition", dataType: "URI", required: true }, { name: "description", dataType: "string", required: true }, { name: "properties", dataType: "JSON", required: false }], help: "Visualize through a table the ObservedProperties of this STAPlus service.", helpEdit: "Create, edit or delete an ObservedProperty in a STAPlus service." },
	Parties: { singular: "Party", entities: [{ name: "Datastreams", required: false }, { name: "MultiDatastreams", required: false }, { name: "Campaigns", required: false }, { name: "ObservationGroups", required: false }, { name: "Things", required: false }], properties: [{ name: "description", dataType: "string", required: false }, { name: "authId", dataType: "string", required: false }, { name: "role", dataType: "PartyRoleCode", required: true }, { name: "displayName", dataType: "string", required: false }], help: "Visualize through a table the Parties of this STAPlus service.", helpEdit: "Create, edit or delete a Party in a STAPlus service." },
	Relations: { singular: "Relation", entities: [{ name: "Object", required: true }, { name: "Subject", required: true }, { name: "ObservationGroups", required: false }], properties: [{ name: "role", dataType: "URI", required: true }, { name: "description", dataType: "string", required: false }, { name: "externalObject", dataType: "URI", required: false }, { name: "properties", dataType: "JSON", required: false }], entityRelations: ["Objects", "Subjects"], help: "Visualize through a table the Relations of this STAPlus service", helpEdit: "Create, edit or delete an Relation in a STAPlus service." },
	Sensors: { singular: "Sensor", entities: [{ name: "Datastreams", required: false }, { name: "MultiDatastreams", required: false }], properties: [{ name: "name", dataType: "string", required: true }, { name: "description", dataType: "string", required: true }, { name: "encodingType", dataType: "string", required: true }, { name: "metadata", dataType: "", required: true }, { name: "properties", dataType: "JSON", required: false }], help: "Visualize through a table the Sensors of this STAPlus service.", helpEdit: "Create, edit or delete a Sensor in a STAPlus service." },
	Things: { singular: "Thing", entities: [{ name: "Datastreams", required: false }, { name: "MultiDatastreams", required: false }, { name: "Party", required: true }, { name: "Locations", required: false }, { name: "HistoricalLocations", required: false }], properties: [{ name: "name", dataType: "string", required: true }, { name: "description", dataType: "string", required: true }, { name: "properties", dataType: "JSON", required: false }], help: "Visualize through a table the Things of this STAPlus service.", helpEdit: "Create, edit or delete a Thing in a STAPlus service." }
};
const STAEntitiesArray = Object.keys(STAEntities);
const STAEntitiesType = {
	singular: "STA entity reading tool", plural: "STA entities reading tool",
	singularEdit: "STA entity transaction tool", pluralEdit: "STA entities create, edit or delete tool"
};

const STASpecialQueries = { ObsLayer: { description: {cat: "Capa d'Observations", spa: "Capa de Observations", eng: "Observations Layer"}, query: "Observations?$orderby=phenomenonTime%20desc&$expand=Datastream($select=unitOfMeasurement),Datastream/ObservedProperty($select=name,description,definition),FeatureOfInterest($select=description,feature)&$select=phenomenonTime,result", help: {cat: "Enllaç al servei STAplus per afegir una consulta a aquest URL i obtenir una taula amb phenomenomTime i els resultats de les Observations, les unitsOfMeasurements i l'ObservedProperty dels Datastreams i una descripció del featureOfInterest relacionat.", spa: "Enlace al servicio STAplus para añadir una consulta a esta URL y obtener una tabla con phenomenomTime y los resultados de las Observations, las unitsOfMeasurements y la ObservedProperty de los Datastreams y una descripción del featureOfInterest relacionado.", eng: "Link to STAplus service to add a query to this url to obtain a table with phenomenomTime and results from Observations, unitsOfMeasurements and ObservedProperty from Datastreams and a description from the featureOfInterest related."} } };
const STASpecialQueriesArray = Object.keys(STASpecialQueries);
const STASpecialQueriesType = { singular: {cat: "Consulta complexa", spa: "Consulta compleja", eng: "Complex query"}, plural: {cat: "Consultes complexes", spa: "Consultas complejas", eng: "Complex queries"} };

const STAOperations = {
	RecursiveExpandSTA: { description: {cat: "Expansió recursiva", spa: "Expansión recursiva", eng: "Recursive Expand"}, callSTALoad: true, addSTAQuery: true, help: {cat: "Obté una taula seleccionant algunes columnes i afegint columnes que resulten d'expandir les propietats de les entitats enllaçades de manera recursiva. Cal que estigui connectat a un node SensorThings API o STAplus.", spa: "Se obtiene una tabla seleccionando algunas columnas y añadiendo columnas que resultan de expandir las propiedades de las entidades vinculadas de forma recursiva. Requiere estar conectado a un nodo SensorThings API o STAplus.", eng: "Gets a table by selecting some columns and adding columns by expanding the properties of linked entities recursively. Needs to be connected to a SensorThings API or a STAplus node."} },
	ExpandColumnSTA: { description: {cat: "Expandeix l'entitat", spa: "Expande la entidad", eng: "Expand entity"}, callSTALoad: true, addSTAQuery: true, help: {cat: "S' obté una taula afegint columnes que resulten de l'expansió de les propietats d'una entitat enllaçada. Per exemple, en un Datastream, afegeix les propietats d'ObservedProperties. Cal que estigui connectat a un node SensorThings API o STAplus.", spa: "Se obtiene una tabla añadiendo columnas que resultan de la expansión de las propiedades de una entidad vinculada. Por ejemplo, en un Datastream, añade las propiedades de ObservedProperties. Requiere estar conectado a un nodo SensorThings API o STAplus.", eng: "Gets a table by adding columns resulting of the expansion of the properties of a linked entity. For example, in a Datastream add properties of ObservedProperties. Requeres to be connected to a SensorThings API or a STAplus node."} },
	MergeExpandsSTA: { description: {cat: "Fusiona les expansions", spa: "Fusiona las expansiones", eng: "Merge Expands"}, callSTALoad: true, addSTAQuery: true, help: {cat: "S'obté una taula fusionant els camps de dues branques originades com a expansió de la mateixa entitat. Per exemple, en un node Datastream, una branca iniciada expandint les propietats d'ObservedProperties i una branca iniciada expandint les propietats de Thing es poden fusionar en una sola branca connectant les dues branques com a entrades d'aquest node.", spa: "Se obtiene una tabla fusionando los campos de dos ramas originadas como expansión de la misma entidad. Por ejemplo, en un nodo Datastream, una rama iniciada expandiendo las propiedades de ObservedProperties y una rama iniciada expandiendo las propiedades de Thing se pueden fusionar en una sola rama conectando ambas ramas como entradas de este nodo.", eng: "Gets a table by merging the fields of two branches originated as an expansion of the same entity. For example, in a Datastream node, a branch started by expanding ObservedProperties properties and a branch started by expanding Thing properties can be merged in a single branch by connecting the two branches as inputs to this node."} },
	SelectColumnsSTA: { description: {cat: "Selecciona columnes", spa: "Selecciona columnas", eng: "Select Columns"}, callSTALoad: true, addSTAQuery: true, help: {cat: "S'obté una taula només amb les columnes seleccionades. Cal que estigui connectat a un node SensorThings API o STAplus.", spa: "Se obtiene una tabla solo con las columnas seleccionadas. Requiere que esté conectado a un nodo SensorThings API o STAplus.", eng: "Gets a table only with columns selected. Requeres to be connected to a SensorThings API or a STAplus node."} },
	SelectRowSTA: { description: {cat: "Selecciona una fila", spa: "Selecciona una fila", eng: "Select Row"}, callSTALoad: true, help: {cat: "S'obté una taula només amb el registre seleccionat. Cal que estigui connectat a una altra entitat SensorThings API o STAplus. És necessari un únic registre per relacionar altres entitats amb aquesta i navegar pel model de dades de SensorThings API o STAplus.", spa: "Se obtiene una tabla solo con el registro seleccionado. Requiere estar conectado a otra entidad SensorThings API o STAplus. Se necesita un único registro para relacionar otras entidades con esta y navegar por el modelo de datos de SensorThings API o STAplus.", eng: "Gets a table only with the selected record. Requeres to be connected to another SensorThings API or a STAplus entity. A single record is required to related entities to this one and navegate the SensorThings API or a STAplus data model."} },
	SelectResourceSTA: { description: {cat: "Selecciona un registre", spa: "Seleccionar un registro", eng: "Select Resource"}, callSTALoad: true, help: {cat: "S'obté una taula només amb el recurs seleccionat. Cal que estigui connectat a una altra entitat SensorThings API o STAplus. És necessari un únic registre per relacionar altres entitats amb aquesta i navegar pel model de dades de SensorThings API o STAplus.", spa: "Se obtiene una tabla solo con el recurso seleccionado. Requiere estar conectado a otra entidad SensorThings API o STAplus. Se necesita un único registro para relacionar otras entidades con esta y navegar por el modelo de datos de SensorThings API o STAplus.", eng: "Gets a table only with the selected resource. Requeres to be connected to another SensorThings API or a STAplus entity. A single record is required to related entities to this one and navegate the SensorThings API or a STAplus data model."} },
	FilterRowsSTA: { description: {cat: "Filtra les files", spa: "Filtra las filas", eng: "Filter Rows"}, callSTALoad: true, addSTAQuery: true, help: {cat: "S'obté una taula amb els registres que compleixen les condicions seleccionades. Requereix una connexió a un node SensorThings API o STAplus. Feu doble clic per obrir el diàleg de filtre.", spa: "Se obtiene una tabla con los registros que cumplen las condiciones seleccionadas. Requiere una conexión a un nodo SensorThings API o STAplus. Haga doble clic para abrir el diálogo de filtro.", eng: "Gets a table with the records that match your conditions. Requires a connection to a SensorThings API or STAplus node. Double-click to open the filter dialog."} },
	FilterRowsByTime: { description: {cat: "Filtra les files per temps", spa: "Filtra las filas por tiempo", eng: "Filter Rows by time"}, addSTAQuery: true, help: {cat: "S'obté una taula amb els registres que coincideixen amb un interval de temps determinat. És possible agrupar-los per períodes de temps. Cal que estigui connectat a un node SensorThings API o STAplus.", spa: "Se obtiene una tabla con los registros que coinciden con un intervalo de tiempo seleccionado. Es posible agruparlos por períodos de tiempo. Requiere estar conectado a un nodo SensorThings API o STAplus.", eng: "Gets a table with records that match with a time interval. It is possible to group them by time periods. Requeres to be connected to a SensorThings API or a STAplus node."} },
	GeoFilterPolSTA: { description: {cat: "Filtra les files per polígon", spa: "Filtrar las filas por polígono", eng: "Filter Rows by Polygon"}, addSTAQuery: true, callSTALoad: true, help: {cat: "S'obté una taula amb els registres continguts dins d'un polígon. Cal que estigui connectat a una altra entitat SensorThings API o STAplus i a una taula amb un registre que tingui una geometria (polígon).", spa: "Se obtiene una tabla con los registros contenidos dentro de un polígono. Requiere estar conectado a otra entidad SensorThings API o STAplus y a una tabla con un registro que tenga una geometría (polígono).", eng: "Gets a table with the records within a polygon. Requeres to be connected to another SensorThings API or a STAplus entity and to a table with a record that has a geometry (polygon)."} },
	GeoFilterPntSTA: { description: {cat: "Filtra les files per distància", spa: "Filtrar las filas por distancia", eng: "Filter Rows by Distance"}, addSTAQuery: true, callSTALoad: true, help: {cat: "S'obté una taula amb els registres que es troben a una distància inferior a una distància donada respecte d'un punt. Cal que estigui connectat a un node SensorThings API o STAplus.", spa: "Se obtiene una tabla con los registros que se encuentran a una distancia inferior a una distancia dada respecto de un punto. Requiere estar conectado a un nodo SensorThings API o STAplus.", eng: "Gets a table with the records that are closer that a given distance of a point. Requeres to be connected to a SensorThings API or a STAplus node."} },
	SortBySTA: { description: {cat: "Ordena per", spa: "Ordenar por", eng: "Sort by"}, callSTALoad: true, addSTAQuery: true, help: {cat: "S'obté una taula amb les dades ordenades segons un criteri determinat. Cal que estigui connectat a un node SensorThings API o STAplus.", spa: "Se obtiene una tabla con los datos ordenados según un criterio determinado. Requiere estar conectado a un nodo SensorThings API o STAplus.", eng: "Gets a table with data sorted by a given criteria. Requeres to be connected to a SensorThings API or a STAplus node."} },
	RangeSTA: { description: {cat: "Interval de registres", spa: "Intervalo de registros", eng: "Record range"}, callSTALoad: true, addSTAQuery: true, help: {cat: "S'obté una taula amb un subconjunt dels registres limitant el nombre de registres i ometent-ne alguns d'inicials. <hr><small>Implementa $top i $skip. Cal que estigui connectat a un node SensorThings API o STAplus</small>.", spa: "Obtiene una tabla con un subconjunto de los registros limitando el número de registros y omitiendo algunos iniciales. <hr><small>Implementa $top y $skip. Requiere estar conectado a un nodo SensorThings API o STAplus</small>.", eng: "Gets a table with a subset of the records limiting the number of records and skiping some initial records. <hr><small>Implements $top and $skip. Requeres to be connected to a SensorThings API or a STAplus node</small>."} },
	UploadObservations: { description: {cat: "Puja a STA", spa: "Subir a STA", eng: "Upload in STA"}, leafNode: true, help: {cat: "Desa algunes observacions en un servidor SensorThings API o STAplus.", spa: "Guarda algunas observaciones en un servidor SensorThings API o STAplus.", eng: "Saves some observations to a SensorThings API or a STAplus server."} },
	CalculateStatisticsSTA: { description: {cat: "Puja les estadístiques a STA", spa: "Subir estadísticas a STA", eng: "Upload statistics in STA"}, leafNode: true, help: {cat: "Desa les estadístiques d'Observations a un servidor SensorThings API o STAplus.", spa: "Guarda las estadísticas de Observations en un servidor SensorThings API o STAplus.", eng: "Saves statistics of Observations in SensorThings API or a STAplus server."} },
	//UploadTimeAverages: {description: "Upload time averages", leafNode: true},
	CountResultsSTA: { description: {cat: "Compta els resultats", spa: "Conta los resultados", eng: "Count results"}, leafNode: true, help: {cat: "Retorna el nombre total de registres que retorna la consulta a l'API sense carregar-los en una taula. Només amb dades STA. Cal que estigui connectat a un node d'entitat SensorThings API o STAplus. Aquest node no es pot connectar a altres nodes dependents.", spa: "Devuelve el número total de registros que devuelve la consulta a la API sin cargarlos en una tabla. Solo con datos STA. Requiere estar conectado a un nodo de entidad SensorThings API o STAplus. Este nodo no puede conectarse a otros nodos dependientes.", eng: "Returns the total number of records returned by the API query without loading them in a table. Only with STA data. Requeres to be connected to a SensorThings API or a STAplus entity node. This node can not be connected to other dependend nodes."} },
	ViewQuerySTA: { description: {cat: "Visualitza la consulta", spa: "Ver la consulta", eng: "View Query"}, leafNode: true, help: {cat: "Mostra en un quadre de diàleg l'URL complet que s'utilitza per fer la consulta per obtenir les dades d'un servei o d'una API del node dependent. Com que l'URL que hi ha darrere del node actiu sempre es representa a l'àrea de consulta i de taula, l'ús d'aquesta operació ja no és recomanable.", spa: "Muestra en un cuadro de diálogo la URL completa que se utiliza para hacer la consulta para obtener los datos de un servicio o de una API del nodo dependiente. Dado que la URL que hay detrás del nodo activo siempre se representa en el área de consulta y de tabla, el uso de esta operación ya no es recomendable.", eng: "Shows the completed URL that is used to make the query to obtain the data from a service or an API of the depended node in a dialog box. Since the URL behind the active node is always represented in the query and table area, the use of this operation is no longer recommended."} },
	OneValueSTA: { description: {cat: "Un valor", spa: "Un valor", eng: "One Value"}, leafNode: true, help: {cat: "Mostra l'últim valor publicat. Aquest valor s'actualitza segons el període de temps que s'estableixi. Cal que estigui connectat a una altra entitat SensorThings API o STAplus. Si WebSub està disponible, se subscriu a un tema, obre una connexió websocket i espera actualitzacions; si no, genera una petició HTTP cada n segons. No cal connectar-lo a una eina d'ordenació temporal. Aquest node no es pot connectar a altres nodes dependents.", spa: "Muestra el último valor publicado. Este valor se actualiza según el período de tiempo que se establezca. Requiere estar conectado a otra entidad SensorThings API o STAplus. Si WebSub está disponible, se suscribe a un tema, abre una conexión websocket y espera actualizaciones; si no, genera una solicitud HTTP cada n segundos. No es necesario conectarlo a una herramienta de ordenación temporal. Este nodo no puede conectarse a otros nodos dependientes.", eng: "Shows the last posted value. This value is updated according to the time period you set. Requeres to be connected to another SensorThings API or a STAplus entity. If WebSub available, it subscribes to a topic, opens a websocket connection and waits for updates, if not, it generates a HTTP request every n seconds. Do not requre to connect to previous sort by time. This node can not be connected to other dependend nodes."} },
	SubscribeSTA: { description: {cat: "Subscripció i alerta", spa: "Suscripción y alerta", eng: "Subscribe and alert"}, help: {cat: "Se subscriu a les notificacions de canvi del recurs pare. Cal que el node pare sigui un STA o un STAplus amb WebSub disponible. Després se subscriu a un tema, obre una connexió websocket i espera actualitzacions. Quan es reben registres nous, s'afegeixen immediatament a la taula.", spa: "Se suscribe a las notificaciones de cambio del recurso padre. Requiere que el nodo padre sea un STA o un STAplus con WebSub disponible. Luego se suscribe a un tema, abre una conexión websocket y espera actualizaciones. Cuando se reciben registros nuevos, se añaden inmediatamente a la tabla.", eng: "Subscribes to notifications of change in the parent resource. It requires that the parent node is a STA or STAplus with WebSub available. Then it subscribes to a topic and opens a websocket connection and waits for updates. When new records are received, they are immediately added to the table."} }
};
const STAOperationsArray = Object.keys(STAOperations);
const STAOperationsType = { singular: {cat: "Eina STA", spa: "Herramienta STA", eng: "STA tool"}, plural: {cat: "Eines STA", spa: "Herramientas STA", eng: "STA tools"} };

const TableOperations = {
	Table: { description: {cat: "Visualitza la taula", spa: "Ver la tabla", eng: "View Table"}, leafNode: true, help: {cat: "Mostra en un quadre de diàleg la taula del node dependent. Com que la taula que hi ha darrere del node actiu es representa a l'àrea de taula, l'ús d'aquesta operació ja no és recomanable.", spa: "Muestra en un cuadro de diálogo la tabla del nodo dependiente. Dado que la tabla que hay detrás del nodo activo se representa en el área de tabla, el uso de esta operación ya no es recomendable.", eng: "Shows a table of the dependent node in a dialog box. Since the table behind the active node is represented in the table area, the use of this operation is no longer recommended."} },
	EditRecord: { description: {cat: "Edita registres", spa: "Editar registros", eng: "Edit record"}, help: {cat: "Mostra i permet editar els registres de la taula del node relacionat. NOTA: Si utilitzeu dades d'un servei web i torneu a demanar les dades, aquest canvi es perdrà.", spa: "Muestra y permite editar los registros de la tabla del nodo relacionado. NOTA: Si utiliza datos de un servicio web y vuelve a pedir los datos, este cambio se perderá.", eng: "Shows and allows editing a record in the table of the related node. NOTE: If you are using data from a web service and you ask for data again, this change will be lost."} },
	Meaning: { description: {cat: "Significat de la columna", spa: "Significado de la columna", eng: "Column meaning"}, help: {cat: "Mostra i permet editar la semàntica (definició i unitats de mesura) de les columnes de la taula.", spa: "Muestra y permite editar la semántica (definición y unidades de medida) de las columnas de la tabla.", eng: "Shows and allows editing the semantics (definition and units of measure) of the table columns."} },
	SelectColumnsTable: { description: {cat: "Selecciona columnes", spa: "Selecciona columnas", eng: "Select Columns"}, help: {cat: "S'obté una taula només amb les columnes seleccionades. No és recomanable per a entitats de SensorThings API o STAplus, ja que elimina l'URL STA.", spa: "Se obtiene una tabla solo con las columnas seleccionadas. No se recomienda para entidades de SensorThings API o STAplus, ya que elimina la URL STA.", eng: "Obtains a table only with the selected columns. Not recommended for SensorThings API or a STAplus entities as it removes the STA URL."} },
	SelectRowTable: { description: {cat: "Selecciona una fila", spa: "Selecciona una fila", eng: "Select Row"}, help: {cat: "S'obté una taula només amb el registre seleccionat. No és recomanable per a entitats de SensorThings API o STAplus, ja que elimina l'URL STA.", spa: "Se obtiene una tabla solo con el registro seleccionado. No se recomienda para entidades de SensorThings API o STAplus, ya que elimina la URL STA.", eng: "Obtains a table only with the selected record. Not recommended for SensorThings API or a STAplus entities as it removes the STA URL."} },
	FilterRowsTable: { description: {cat: "Filtra files", spa: "Filtra filas", eng: "Filter Rows"}, help: {cat: "S'obté una taula amb els registres que compleixen les condicions seleccionades. No és recomanable per a entitats de SensorThings API o STAplus, ja que elimina l'URL STA.", spa: "Obtiene una tabla con los registros que cumplen las condiciones seleccionadas. No se recomienda para entidades de SensorThings API o STAplus, ya que elimina la URL STA.", eng: "Obtain a table with the records that match the contitions. Not recommended for SensorThings API or a STAplus entities as it removes the STA URL."} },
	Replace: { description: {cat: "Substitueix", spa: "Sustituir", eng: "Replace"}, help: {cat: "Cerca i substitueix text, números o dates en una columna o a tota la taula", spa: "Buscar y sustituir texto, números o fechas en una columna o en toda la tabla", eng: "Find and replace text, numbers, or data in one column or across the whole table"} },
	JoinTables: { description: {cat: "Unió de taules", spa: "Unir tablas", eng: "Join Tables"}, help: {cat: "Crea una única taula que és el resultat d'unir dues taules utilitzant els valors d'algunes columnes seleccionades a totes dues taules per definir el criteri de fusió.", spa: "Crea una única tabla que es el resultado de unir dos tablas utilizando los valores de algunas columnas seleccionadas en ambas tablas para definir el criterio de fusión.", eng: "Creates a single table that is the result of joining two tables using some selected column values in both tables to defined the merge criteria."} },
	ConcatenateTables: { description: {cat: "Concatena  columnes", spa: "Concatena columnas", eng: "Concatenate Columns"}, help: {cat: "Crea una única taula afegint els registres de la segona taula a la primera. Les columnes amb el mateix nom a totes dues taules es fusionen en una sola columna.", spa: "Crea una única tabla añadiendo los registros de la segunda tabla a la primera. Las columnas con el mismo nombre en ambas tablas se fusionan en una sola columna.", eng: "Create a single table by adding the records of the second table to the first one. The columns with the same name in both tables are merged in a sigle column."} },
	GroupBy: { description: {cat: "Agrupa per", spa: "Agrupar por", eng: "Group by"}, help: {cat: "Crea una taula amb les columnes que contenen les estadístiques seleccionades de l'agregació d'alguns registres que tenen els mateixos valors en altres columnes seleccionades.", spa: "Crea una tabla con las columnas que contienen las estadísticas seleccionadas de la agregación de algunos registros que tienen los mismos valores en otras columnas seleccionadas.", eng: "Creates a table will the columns containng selected statistics of the aggregation of some records that have the same values other selected columns."} },
	SortByTables: { description: {cat: "Ordena per", spa: "Ordenar por", eng: "Sort by"}, callSTALoad: true, help: {cat: "S'obté una taula amb les dades ordenades segons un criteri determinat.", spa: "Se obtiene una tabla con los datos ordenados según un criterio determinado.", eng: "Gets a table with data sorted by a given criteria."} },
	AggregateColumns: { description: {cat: "Agrega  columnes", spa: "Agrega columnas", eng: "Aggregate Columns"}, help: {cat: "Afegeix una nova columna a la taula amb l'agregació d'altres columnes seleccionades prèviament.", spa: "Añade una nueva columna a la tabla con la agregación de otras columnas seleccionadas previamente.", eng: "Adds a new column to a table with the aggregation of other previous selected columns."} },
	CreateColumns: { description: {cat: "Crea columnes", spa: "Crea columnas", eng: "Create Columns"}, help: {cat: "Afegeix una nova columna a la taula. Aquesta columna es pot deixar buida, omplir amb un valor constant o omplir amb un valor autoincremental.", spa: "Añade una nueva columna a la tabla. Esta columna se puede dejar vacía, rellenar con un valor constante o rellenar con un valor autoincremental.", eng: "Adds a new column to your table. This column can be left empty, filled with a constant value or filled with an autoincremental value."} },
	AddColumnPnt: { description: {cat: "Afegeix una columna de punt", spa: "Añadir columna de punto", eng: "Add point column"}, help: {cat: "Afegeix a la vostra taula una nova columna de punt que és una transformació de format d'una columna de punt preexistent. La columna pot ser una geometria GeoJSON (punt), un Well Known Text (punt), DGGS (zona poligonal) o un parell de columnes de longitud/latitud.", spa: "Añade a su tabla una nueva columna de punto que es una transformación de formato de una columna de punto preexistente. La columna puede ser una geometría GeoJSON (punto), un Well Known Text (punto), DGGS (zona poligonal) o un par de columnas de longitud/latitud.", eng: "Adds a new point column to your table that is a format transformation of a preexisting point column. The column can be a GeoJSON geometry (point), a Well Known Text (point), DGGS (polygon zone), or a pair of longitude/latitude columns."}},
	AddColumnBBox: { description: {cat: "Afegeix una columna BBox", spa: "Añadir columna BBox", eng: "Add BBox column"}, help: {cat: "Afegeix a la vostra taula una nova columna de BBox (caixa envoltant) que és una transformació de format d'una columna de BBox preexistent. La columna pot ser una geometria GeoJSON (polígon), un Well Known Text (polígon) o quatre columnes amb coordenades de longitud/latitud.", spa: "Añade a su tabla una nueva columna de BBox (caja envolvente) que es una transformación de formato de una columna de BBox preexistente. La columna puede ser una geometría GeoJSON (polígono), un Well Known Text (polígono) o cuatro columnas con coordenadas de longitud/latitud.", eng: "Adds a new bounding box column to your table that is a format transformation of a preexisting bounding box column. The column can be a GeoJSON geometry (polygon), a Well Known Text (polygon), or four columns with longitude/latitude coordinates."}},
	ColumnsCalculator: { description: {cat: "Calculadora de columnes", spa: "Calculadora de columnas", eng: "Columns calculator"}, help: {cat: "Afegeix una nova columna a la vostra taula on, per a cada registre, la nova columna conté el resultat d'una operació que utilitza altres valors de columna d'aquell registre.", spa: "Añade una nueva columna a su tabla donde, para cada registro, la nueva columna contiene el resultado de una operación que utiliza otros valores de columna de ese registro.", eng: "Adds a new column to your table where for each record the new column contains the result of an operation involving other column values of that record."} },
	PivotTable: { description: {cat: "Taula dinàmica", spa: "Tabla dinámica", eng: "Pivot table"}, help: {cat: "Crea una nova taula on el contingut d'algunes columnes es transposa en noves columnes", spa: "Crea una nueva tabla donde el contenido de algunas columnas se transpone en nuevas columnas", eng: "Create a new table where some column content is transponsed into new columns"} },
	TransposeTable: { description: {cat: "Transposa la taula", spa: "Transponer la tabla", eng: "Transpose table"}, help: {cat: "Intercanvia files i columnes; els nous noms de columna provenen dels valors d'una columna de capçalera escollida.", spa: "Intercambia filas y columnas; los nuevos nombres de columna provienen de los valores de una columna de cabecera elegida.", eng: "Swap rows and columns; new column names come from values of a chosen header column."} },
	ColumnStatistics: { description: {cat: "Estadístiques de les columnes", spa: "Estadísticas de las columnas", eng: "Columns statistics"}, help: {cat: "Crea una taula on, per a cada columna, es calculen les estadístiques principals dels valors de la columna de tots els registres.", spa: "Crea una tabla donde, para cada columna, se calculan las estadísticas principales de los valores de la columna de todos los registros.", eng: "Create a table where, for each column the main statistics for the column values of all records are recorded."} },
	SeparateColumns: { description: {cat: "Separa les columnes", spa: "Separa columnas", eng: "Separate Columns"}, help: {cat: "Divideix una columna que conté un objecte JSON en noves columnes separades i elimina la columna original.", spa: "Divide una columna que contiene un objeto JSON en nuevas columnas separadas y elimina la columna original.", eng: "Splits a column containing a JSON object into separated new columns and removes the original column."} },
	SaveTable: { description: {cat: "Desa la taula", spa: "Guardar la tabla", eng: "Save Table"}, leafNode: true, help: {cat: "Desa la taula continguda en el node com a CSV (i CSVW si la definició de les columnes està enriquida semànticament; vegeu 'meaning').", spa: "Guarda la tabla contenida en el nodo como CSV (y CSVW si la definición de las columnas está enriquecida semánticamente; véase 'meaning').", eng: "Saves the table contained in the node as a CSV (and CSVW if the column definition is semantically enriched; see &#39;meaning&#39;)."} },
	SaveLayer: { description: {cat: "Desa la capa", spa: "Guardar la capa", eng: "Save Layer"}, leafNode: true, help: {cat: "Desa la taula com un GeoJSON. Requereix dues columnes amb valors de latitud i longitud.", spa: "Guarda la tabla como un GeoJSON. Requiere dos columnas con valores de latitud y longitud.", eng: "Saves the table as a GeoJSON. It requires two columns with a latitude and longitude values."} },
	guf: { description: {cat: "Comentaris/suggeriments", spa: "Comentarios/Sugerencias", eng: "Feedback"}, help: {cat: "Recupera els \"geospatial user feedback\" (comentaris/suggeriments)  relacionats amb l'única fila present a la taula (p. ex. un registre d'un catàleg CSW). També permet afegir o editar comentaris. Utilitza el repositori i la interfície de NiMMbus.", spa: "Recupera los comentarios \"geospatial user feedback\" (comentarios/sugerencias) con la única fila presente en la tabla (p. ej. un registro de un catálogo CSW). También permite añadir o editar comentarios. Utiliza el repositorio y la interfaz de NiMMbus.", eng: "Retreives the geospatial user feedback related to the single row present in the table (e.g. a record forma CSW catalogue). It also allows for adding or editing feedback. It uses the NiMMbus repository and interface."} },
	uploadToIC: { description: {cat: "Puja al catàleg immutable", spa: "Subir al catálogo inmutable", eng: "Upload to inmutable catalog"}, leafNode: true, help: {cat: "Puja les dades i les metadades a un catàleg immutable.", spa: "Sube los datos y los metadatos a un catálogo inmutable.", eng: "Upload data and metadata to an inmutable catalog."} }
};

const TableOperationsArray = Object.keys(TableOperations);
const TableOperationsType = { singular: {cat: "Eina general per taula ", spa: "Herramienta general para  tabla ", eng: "Generic table tool"}, plural: {cat: "Eines generals per a taules", spa: "Herramientas generales para tablas", eng: "Generic table tools"} };

const tableStatisticsVisualize = {
	ColumnStatistics: { description: {cat: "Estadístiques de columnes", spa: "Estadísticas de columnas", eng: "Columns statistics"}, leafNode: true, help: {cat: "Crea una taula on, per a cada columna, es calculen les estadístiques principals dels valors de la columna de tots els registres.", spa: "Crea una tabla donde, para cada columna, se calculan las estadísticas principales de los valores de la columna de todos los registros.", eng: "Create a table where, for each column the main statistics for the column values of all records are recorded."} },
	ScatterPlot: { description: {cat: "Gràfic de dispersió", spa: "Gráfico de dispersión", eng: "Scatter Plot"}, leafNode: true, help: {cat: "Crea un gràfic de dispersió amb els valors de la columna d'una taula.", spa: "Crea un gráfico de dispersión con los valores de la columna de una tabla.", eng: "Creates a scatter plot with a the values of the column of a table."} },
	BarPlot: { description: {cat: "Gràfic de barres", spa: "Gráfico de barras", eng: "Bar Plot"}, leafNode: true, help: {cat: "Crea un gràfic de barres o de sectors amb els valors de la columna d'una taula.", spa: "Crea un gráfico de barras o de sectores con los valores de la columna de una tabla.", eng: "Create a bar or pie chart with a the values of the column of a table."} },
	RadarPlot: { description: {cat: "Gràfic de radar", spa: "Gráfico de radar", eng: "Radar Plot"}, leafNode: true, help: {cat: "Crea un gràfic de radar (aranya). Afegeix les sèries una a una, com al gràfic de dispersió.", spa: "Crea un gráfico de radar (araña). Añade las series una a una, como en el gráfico de dispersión.", eng: "Create a radar (spider) chart. Add series one by one, like the Scatter Plot."} },
	ImageViewer: { description: {cat: "Visor d'imatges", spa: "Visor de imágenes", eng: "Image Viewer"}, leafNode: true, help: {cat: "Mostra les imatges referenciades d'una columna. Considera que el contingut de la columna són URL d'imatges compatibles amb el navegador (habitualment en format JPEG o PNG).", spa: "Muestra las imágenes referenciadas de una columna. Supone que el contenido de la columna son URL de imágenes compatibles con el navegador (habitualmente en formato JPEG o PNG).", eng: "Shows the pictures referenced by a column. Assumes that the content of the column are url to images supported by the browser (commonly in JPEG or PNG format)."} },
	OpenMap: { description: {cat: "Obre a un mapa", spa: "Abrir en un mapa", eng: "Open Map"}, leafNode: true, help: {cat: "Obre una taula com un mapa en una interfície d'un navegador de mapes. Requereix dues columnes amb valors de latitud i longitud.", spa: "Abre una tabla como un mapa en una interfaz de un navegador de mapas. Requiere dos columnas con valores de latitud y longitud.", eng: "Opens a table as a map in a map browser interface. It requires two columns with a latitude and longitude values."} }
}
const tableStatisticsVisualizeArray = Object.keys(tableStatisticsVisualize);
const tableStatisticsVisualizeType = { singular: {cat: "Eina de taula per a estadístiques i visualització", spa: "Herramienta de tabla para estadísticas y visualización", eng: "Table tool for statistics and visualization"}, plural: {cat: "Eines de taula per a estadístiques i visualització", spa: "Herramientas de tabla para estadísticas y visualización", eng: "Table tools for statistics and visualization"} };

const dataQuality = {
	uncertainty: { description: {cat: "Incertesa", spa: "Incertidumbre", eng: "Uncertainty"}, help: {cat: "Agrupa els valors per temps i espai i en calcula les incerteses", spa: "Agrupa los valores por tiempo y espacio y calcula sus incertidumbres", eng: "Group values by time and space and calculate its uncertainties"} },
	completness: { description: {cat: "Completesa", spa: "Completitud", eng: "Completeness"}, help: {cat: "Comprovacions opcionals (només xifres, sense aprovat/suspens). Omissió: valors buits o absents en una columna (indicador d'omissió opcional). Comissió (duplicats): registres duplicats en una columna (opcionalment, tracta les majúscules i les minúscules com a idèntiques; indicador de duplicat opcional). Excés de comissió: registres addicionals més enllà del recompte de registres esperat.", spa: "Comprobaciones opcionales (solo cifras, sin aprobado/suspenso). Omisión: valores vacíos o ausentes en una columna (indicador de omisión opcional). Comisión (duplicados): registros duplicados en una columna (opcionalmente, trata las mayúsculas y las minúsculas como idénticas; indicador de duplicado opcional). Exceso de comisión: registros adicionales más allá del recuento de registros esperado.", eng: "Optional checks (numbers only, no pass/fail). Omission: empty or missing values in a column (optional Omission Flag). Commission (duplicates): duplicated records in a column (optional treat uppercase and lowercase as identical; optional Duplicate Flag). Commission excess: extra records beyond an expected record count (excess = max(0, total − expected); excess rate = excess / total)."} },
	misclassificationMatrix: { description: {cat: "Matriu de confusió", spa: "Matriz de confusión", eng: "Misclassification Matrix"}, help: {cat: "El grau en què les classificacions assignades es corresponen amb les classificacions de referència, representat mitjançant una matriu d'elements classificats correctament i incorrectament", spa: "El grado en que las clasificaciones asignadas se corresponden con las clasificaciones de referencia, representado mediante una matriz de elementos clasificados correcta e incorrectamente", eng: "The degree to which the assigned classifications correspond to the reference classifications, as represented by a matrix of correctly and incorrectly classified items"} },
	logicalConsistency: { description: {cat: "Consistència lògica", spa: "Consistencia lógica", eng: "Logical consistency"}, help: {cat: "Fa una comprovació de consistència lògica per identificar contradiccions i garantir relacions coherents entre les dades.", spa: "Realiza una comprobación de consistencia lógica para identificar contradicciones y garantizar relaciones coherentes entre los datos.", eng: "Performs a logical consistency check to identify contradictions and ensure coherent data relationships."} },
	formatConsistency: { description: {cat: "Consistència de format", spa: "Consistencia de formato", eng: "Format consistency"}, help: {cat: "Comprova que els valors segueixen el format esperat.", spa: "Comprueba que los valores siguen el formato esperado.", eng: "Checks that values follow the expected format."} },
	temporalQuality: { description: {cat: "Qualitat temporal", spa: "Calidad temporal", eng: "Temporal quality"}, help: {cat: "Permet calcular la consistència temporal, la validesa temporal i la resolució temporal.", spa: "Permite calcular la consistencia temporal, la validez temporal y la resolución temporal.", eng: "Allows calculating temporal consistency, temporal validity and temporal resolution."} },
	positionalQuality: { description: {cat: "Qualitat posicional", spa: "Calidad posicional", eng: "Positional quality"}, help: {cat: "Permet calcular l'exactitud posicional i la validesa posicional", spa: "Permite calcular la exactitud posicional y la validez posicional", eng: "Allows calculating positional accuracy and positional validity"} },
	thematicQuality: { description: {cat: "Qualitat temàtica", spa: "Calidad temática", eng: "Thematic quality"}, help: {cat: "Permet calcular l'exactitud temàtica i la validesa temàtica", spa: "Permite calcular la exactitud temática y la validez temática", eng: "Allows calculating thematic accuracy and thematic validity"} },
	qualityResultsViewer: { description: {cat: "Visor dels resultats de qualitat", spa: "Visor de los resultados de calidad", eng: "Quality results viewer"}, help: {cat: "Permet visualitzar els resultats complets del node de qualitat enllaçat", spa: "Permite visualizar los resultados completos del nodo de calidad vinculado", eng: "Allows you to visualize the complete results from the linked quality node"} }

}
const dataQualityArray = Object.keys(dataQuality);
const dataQualityType = { singular: {cat: "Eina de taula per a la qualitat de les dades", spa: "Herramienta de tabla para la calidad de los datos", eng: "Table tool for data quality"}, plural: {cat: "Eines de taula per a la qualitat de les dades", spa: "Herramientas de tabla para la calidad de los datos", eng: "Table tools for data quality"} }